# Introduction

This is a sample repo with one flow (`test_<step>`, where <step> is a number) that tries to exemplify how you build a functional app progressively. 

If you are here it means you successfully cloned the project into AEP GUI; congratulations!

# What do to first

1. select namespace `test` 
2. go to Design/Libraries and upload all libraries into runtime (all labels should be green)
3. go to Environment settings/Ingress queues and for queue name `dispatch-script` select the dispatch lib `generic-dispatch` from drop down box
4. go to Design/Flows and upload all flows into runtime (all labels should be green)
5. go to "Flow test data"  and select the queuedb (only one option in drop down box) plus the rte instance (`queue name` drop down box; there will be several entries, select the one that starts with `rte`)

Now you are good to go! 

# Test step 1 

In this step, you will execute flow test_1 which does not do anything; but it shows how you can do tracing. 

```bash
curl -k "https://10.211.55.4:8883/test?flowname=test:induction:test_1"
```

Go to AEP GUI, Runtime View (left side menu), Traces and from drop down box `Flows?` select the flow `induction:test_1` and in the table you should see a row for each session that used this flow. 

Select it (left side buttons on the table row) to see the traces either as a list or as a diagram. 

## As a list

When you check the session tracing in list mode, for each state traversed by the session there is a row; selecting the row it shows the full context used at that time during execution (current event, current session, any errors, etc).

Red lines are incoming events from external systems and blue lines are responses generated by AEP or new requests to external systems made by AEP. 

Select the first line and check the "initial"  slot in the JSON editor; this is the actual event after decoding and pre-processing that AEP receives. 

In this way you can learn the structure of events iteratively; we encourage an exploratory development style. 

## As a diagram

When you check session tracing in diagram mode, the states traversed by the session during execution are highlighted in green; you can select a state and right click on it, press "View session" in the 
context menu to see again the full info about state of engine during execution at this point. 


Now that you can check the structure of event you receive (fields, values, etc), let's go forward and look at the next step

# Test step 2

In this step, we will execute the flow "test_2"; you can open it up (left side menu, Design/Flows and press the open button on the row). 

Run the statement:

```bash
curl -k "https://10.211.55.4:8883/test?flowname=test:induction:test_2"
```

You should receive back the proverbial "Hello World!" message! 

Go ahead and check the trace as well as comments in the flow diagram! 

What you should pay attention to this time:

1. check again the tracing and context available at each state to see how session content changed 
2. we use a new handler for building objects and storing them into session so that they are available as long as session exists; these objects can be created in one instance and available in all other instances, per session. 

# Test step 3